/*
Copyright Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package internalversion

import (
	operators "github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/apis/operators"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PackageManifestLister helps list PackageManifests.
// All objects returned here must be treated as read-only.
type PackageManifestLister interface {
	// List lists all PackageManifests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operators.PackageManifest, err error)
	// PackageManifests returns an object that can list and get PackageManifests.
	PackageManifests(namespace string) PackageManifestNamespaceLister
	PackageManifestListerExpansion
}

// packageManifestLister implements the PackageManifestLister interface.
type packageManifestLister struct {
	listers.ResourceIndexer[*operators.PackageManifest]
}

// NewPackageManifestLister returns a new PackageManifestLister.
func NewPackageManifestLister(indexer cache.Indexer) PackageManifestLister {
	return &packageManifestLister{listers.New[*operators.PackageManifest](indexer, operators.Resource("packagemanifest"))}
}

// PackageManifests returns an object that can list and get PackageManifests.
func (s *packageManifestLister) PackageManifests(namespace string) PackageManifestNamespaceLister {
	return packageManifestNamespaceLister{listers.NewNamespaced[*operators.PackageManifest](s.ResourceIndexer, namespace)}
}

// PackageManifestNamespaceLister helps list and get PackageManifests.
// All objects returned here must be treated as read-only.
type PackageManifestNamespaceLister interface {
	// List lists all PackageManifests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operators.PackageManifest, err error)
	// Get retrieves the PackageManifest from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*operators.PackageManifest, error)
	PackageManifestNamespaceListerExpansion
}

// packageManifestNamespaceLister implements the PackageManifestNamespaceLister
// interface.
type packageManifestNamespaceLister struct {
	listers.ResourceIndexer[*operators.PackageManifest]
}
