// Code generated by counterfeiter. DO NOT EDIT.
package listers

import (
	"sync"

	v1a "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers/core/v1"
)

type FakeServiceNamespaceLister struct {
	GetStub        func(string) (*v1a.Service, error)
	getMutex       sync.RWMutex
	getArgsForCall []FakeServiceNamespaceListerGetArgs
	getReturns     struct {
		result1 *v1a.Service
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 *v1a.Service
		result2 error
	}
	ListStub        func(labels.Selector) ([]*v1a.Service, error)
	listMutex       sync.RWMutex
	listArgsForCall []FakeServiceNamespaceListerListArgs
	listReturns     struct {
		result1 []*v1a.Service
		result2 error
	}
	listReturnsOnCall map[int]struct {
		result1 []*v1a.Service
		result2 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// FakeServiceNamespaceListerGetArgs holds the arguments of one call to Get.
type FakeServiceNamespaceListerGetArgs struct {
	Arg1 string
}

// FakeServiceNamespaceListerListArgs holds the arguments of one call to List.
type FakeServiceNamespaceListerListArgs struct {
	Arg1 labels.Selector
}

func (fake *FakeServiceNamespaceLister) Get(arg1 string) (*v1a.Service, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, FakeServiceNamespaceListerGetArgs{arg1})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeServiceNamespaceLister) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeServiceNamespaceLister) GetCalls(stub func(string) (*v1a.Service, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *FakeServiceNamespaceLister) GetArgsForCall(i int) string {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeServiceNamespaceLister) GetArgs() []FakeServiceNamespaceListerGetArgs {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	args := make([]FakeServiceNamespaceListerGetArgs, len(fake.getArgsForCall))
	copy(args, fake.getArgsForCall)
	return args
}

func (fake *FakeServiceNamespaceLister) GetReturns(result1 *v1a.Service, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *v1a.Service
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceNamespaceLister) GetReturnsOnCall(i int, result1 *v1a.Service, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *v1a.Service
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *v1a.Service
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceNamespaceLister) List(arg1 labels.Selector) ([]*v1a.Service, error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, FakeServiceNamespaceListerListArgs{arg1})
	stub := fake.ListStub
	fakeReturns := fake.listReturns
	fake.recordInvocation("List", []interface{}{arg1})
	fake.listMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeServiceNamespaceLister) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakeServiceNamespaceLister) ListCalls(stub func(labels.Selector) ([]*v1a.Service, error)) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *FakeServiceNamespaceLister) ListArgsForCall(i int) labels.Selector {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	argsForCall := fake.listArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeServiceNamespaceLister) ListArgs() []FakeServiceNamespaceListerListArgs {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	args := make([]FakeServiceNamespaceListerListArgs, len(fake.listArgsForCall))
	copy(args, fake.listArgsForCall)
	return args
}

func (fake *FakeServiceNamespaceLister) ListReturns(result1 []*v1a.Service, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 []*v1a.Service
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceNamespaceLister) ListReturnsOnCall(i int, result1 []*v1a.Service, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 []*v1a.Service
			result2 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 []*v1a.Service
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceNamespaceLister) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeServiceNamespaceLister) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeServiceNamespaceLister) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ v1.ServiceNamespaceLister = new(FakeServiceNamespaceLister)
