// Code generated by counterfeiter. DO NOT EDIT.
package listers

import (
	"sync"

	v1a "k8s.io/api/rbac/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers/rbac/v1"
)

type FakeRoleBindingLister struct {
	ListStub        func(labels.Selector) ([]*v1a.RoleBinding, error)
	listMutex       sync.RWMutex
	listArgsForCall []FakeRoleBindingListerListArgs
	listReturns     struct {
		result1 []*v1a.RoleBinding
		result2 error
	}
	listReturnsOnCall map[int]struct {
		result1 []*v1a.RoleBinding
		result2 error
	}
	RoleBindingsStub        func(string) v1.RoleBindingNamespaceLister
	roleBindingsMutex       sync.RWMutex
	roleBindingsArgsForCall []FakeRoleBindingListerRoleBindingsArgs
	roleBindingsReturns     struct {
		result1 v1.RoleBindingNamespaceLister
	}
	roleBindingsReturnsOnCall map[int]struct {
		result1 v1.RoleBindingNamespaceLister
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// FakeRoleBindingListerListArgs holds the arguments of one call to List.
type FakeRoleBindingListerListArgs struct {
	Arg1 labels.Selector
}

// FakeRoleBindingListerRoleBindingsArgs holds the arguments of one call to RoleBindings.
type FakeRoleBindingListerRoleBindingsArgs struct {
	Arg1 string
}

func (fake *FakeRoleBindingLister) List(arg1 labels.Selector) ([]*v1a.RoleBinding, error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, FakeRoleBindingListerListArgs{arg1})
	stub := fake.ListStub
	fakeReturns := fake.listReturns
	fake.recordInvocation("List", []interface{}{arg1})
	fake.listMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRoleBindingLister) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakeRoleBindingLister) ListCalls(stub func(labels.Selector) ([]*v1a.RoleBinding, error)) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *FakeRoleBindingLister) ListArgsForCall(i int) labels.Selector {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	argsForCall := fake.listArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeRoleBindingLister) ListArgs() []FakeRoleBindingListerListArgs {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	args := make([]FakeRoleBindingListerListArgs, len(fake.listArgsForCall))
	copy(args, fake.listArgsForCall)
	return args
}

func (fake *FakeRoleBindingLister) ListReturns(result1 []*v1a.RoleBinding, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 []*v1a.RoleBinding
		result2 error
	}{result1, result2}
}

func (fake *FakeRoleBindingLister) ListReturnsOnCall(i int, result1 []*v1a.RoleBinding, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 []*v1a.RoleBinding
			result2 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 []*v1a.RoleBinding
		result2 error
	}{result1, result2}
}

func (fake *FakeRoleBindingLister) RoleBindings(arg1 string) v1.RoleBindingNamespaceLister {
	fake.roleBindingsMutex.Lock()
	ret, specificReturn := fake.roleBindingsReturnsOnCall[len(fake.roleBindingsArgsForCall)]
	fake.roleBindingsArgsForCall = append(fake.roleBindingsArgsForCall, FakeRoleBindingListerRoleBindingsArgs{arg1})
	stub := fake.RoleBindingsStub
	fakeReturns := fake.roleBindingsReturns
	fake.recordInvocation("RoleBindings", []interface{}{arg1})
	fake.roleBindingsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRoleBindingLister) RoleBindingsCallCount() int {
	fake.roleBindingsMutex.RLock()
	defer fake.roleBindingsMutex.RUnlock()
	return len(fake.roleBindingsArgsForCall)
}

func (fake *FakeRoleBindingLister) RoleBindingsCalls(stub func(string) v1.RoleBindingNamespaceLister) {
	fake.roleBindingsMutex.Lock()
	defer fake.roleBindingsMutex.Unlock()
	fake.RoleBindingsStub = stub
}

func (fake *FakeRoleBindingLister) RoleBindingsArgsForCall(i int) string {
	fake.roleBindingsMutex.RLock()
	defer fake.roleBindingsMutex.RUnlock()
	argsForCall := fake.roleBindingsArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeRoleBindingLister) RoleBindingsArgs() []FakeRoleBindingListerRoleBindingsArgs {
	fake.roleBindingsMutex.RLock()
	defer fake.roleBindingsMutex.RUnlock()
	args := make([]FakeRoleBindingListerRoleBindingsArgs, len(fake.roleBindingsArgsForCall))
	copy(args, fake.roleBindingsArgsForCall)
	return args
}

func (fake *FakeRoleBindingLister) RoleBindingsReturns(result1 v1.RoleBindingNamespaceLister) {
	fake.roleBindingsMutex.Lock()
	defer fake.roleBindingsMutex.Unlock()
	fake.RoleBindingsStub = nil
	fake.roleBindingsReturns = struct {
		result1 v1.RoleBindingNamespaceLister
	}{result1}
}

func (fake *FakeRoleBindingLister) RoleBindingsReturnsOnCall(i int, result1 v1.RoleBindingNamespaceLister) {
	fake.roleBindingsMutex.Lock()
	defer fake.roleBindingsMutex.Unlock()
	fake.RoleBindingsStub = nil
	if fake.roleBindingsReturnsOnCall == nil {
		fake.roleBindingsReturnsOnCall = make(map[int]struct {
			result1 v1.RoleBindingNamespaceLister
		})
	}
	fake.roleBindingsReturnsOnCall[i] = struct {
		result1 v1.RoleBindingNamespaceLister
	}{result1}
}

func (fake *FakeRoleBindingLister) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRoleBindingLister) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeRoleBindingLister) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ v1.RoleBindingLister = new(FakeRoleBindingLister)
