// Code generated by counterfeiter. DO NOT EDIT.
package listers

import (
	"sync"

	v1a "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers/core/v1"
)

type FakeSecretLister struct {
	ListStub        func(labels.Selector) ([]*v1a.Secret, error)
	listMutex       sync.RWMutex
	listArgsForCall []FakeSecretListerListArgs
	listReturns     struct {
		result1 []*v1a.Secret
		result2 error
	}
	listReturnsOnCall map[int]struct {
		result1 []*v1a.Secret
		result2 error
	}
	SecretsStub        func(string) v1.SecretNamespaceLister
	secretsMutex       sync.RWMutex
	secretsArgsForCall []FakeSecretListerSecretsArgs
	secretsReturns     struct {
		result1 v1.SecretNamespaceLister
	}
	secretsReturnsOnCall map[int]struct {
		result1 v1.SecretNamespaceLister
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// FakeSecretListerListArgs holds the arguments of one call to List.
type FakeSecretListerListArgs struct {
	Arg1 labels.Selector
}

// FakeSecretListerSecretsArgs holds the arguments of one call to Secrets.
type FakeSecretListerSecretsArgs struct {
	Arg1 string
}

func (fake *FakeSecretLister) List(arg1 labels.Selector) ([]*v1a.Secret, error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, FakeSecretListerListArgs{arg1})
	stub := fake.ListStub
	fakeReturns := fake.listReturns
	fake.recordInvocation("List", []interface{}{arg1})
	fake.listMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSecretLister) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakeSecretLister) ListCalls(stub func(labels.Selector) ([]*v1a.Secret, error)) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *FakeSecretLister) ListArgsForCall(i int) labels.Selector {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	argsForCall := fake.listArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeSecretLister) ListArgs() []FakeSecretListerListArgs {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	args := make([]FakeSecretListerListArgs, len(fake.listArgsForCall))
	copy(args, fake.listArgsForCall)
	return args
}

func (fake *FakeSecretLister) ListReturns(result1 []*v1a.Secret, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 []*v1a.Secret
		result2 error
	}{result1, result2}
}

func (fake *FakeSecretLister) ListReturnsOnCall(i int, result1 []*v1a.Secret, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 []*v1a.Secret
			result2 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 []*v1a.Secret
		result2 error
	}{result1, result2}
}

func (fake *FakeSecretLister) Secrets(arg1 string) v1.SecretNamespaceLister {
	fake.secretsMutex.Lock()
	ret, specificReturn := fake.secretsReturnsOnCall[len(fake.secretsArgsForCall)]
	fake.secretsArgsForCall = append(fake.secretsArgsForCall, FakeSecretListerSecretsArgs{arg1})
	stub := fake.SecretsStub
	fakeReturns := fake.secretsReturns
	fake.recordInvocation("Secrets", []interface{}{arg1})
	fake.secretsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSecretLister) SecretsCallCount() int {
	fake.secretsMutex.RLock()
	defer fake.secretsMutex.RUnlock()
	return len(fake.secretsArgsForCall)
}

func (fake *FakeSecretLister) SecretsCalls(stub func(string) v1.SecretNamespaceLister) {
	fake.secretsMutex.Lock()
	defer fake.secretsMutex.Unlock()
	fake.SecretsStub = stub
}

func (fake *FakeSecretLister) SecretsArgsForCall(i int) string {
	fake.secretsMutex.RLock()
	defer fake.secretsMutex.RUnlock()
	argsForCall := fake.secretsArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeSecretLister) SecretsArgs() []FakeSecretListerSecretsArgs {
	fake.secretsMutex.RLock()
	defer fake.secretsMutex.RUnlock()
	args := make([]FakeSecretListerSecretsArgs, len(fake.secretsArgsForCall))
	copy(args, fake.secretsArgsForCall)
	return args
}

func (fake *FakeSecretLister) SecretsReturns(result1 v1.SecretNamespaceLister) {
	fake.secretsMutex.Lock()
	defer fake.secretsMutex.Unlock()
	fake.SecretsStub = nil
	fake.secretsReturns = struct {
		result1 v1.SecretNamespaceLister
	}{result1}
}

func (fake *FakeSecretLister) SecretsReturnsOnCall(i int, result1 v1.SecretNamespaceLister) {
	fake.secretsMutex.Lock()
	defer fake.secretsMutex.Unlock()
	fake.SecretsStub = nil
	if fake.secretsReturnsOnCall == nil {
		fake.secretsReturnsOnCall = make(map[int]struct {
			result1 v1.SecretNamespaceLister
		})
	}
	fake.secretsReturnsOnCall[i] = struct {
		result1 v1.SecretNamespaceLister
	}{result1}
}

func (fake *FakeSecretLister) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSecretLister) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeSecretLister) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ v1.SecretLister = new(FakeSecretLister)
