/*
Copyright Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/operator-framework/api/pkg/operators/v1"
	scheme "github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OLMConfigsGetter has a method to return a OLMConfigInterface.
// A group's client should implement this interface.
type OLMConfigsGetter interface {
	OLMConfigs() OLMConfigInterface
}

// OLMConfigInterface has methods to work with OLMConfig resources.
type OLMConfigInterface interface {
	Create(ctx context.Context, oLMConfig *v1.OLMConfig, opts metav1.CreateOptions) (*v1.OLMConfig, error)
	Update(ctx context.Context, oLMConfig *v1.OLMConfig, opts metav1.UpdateOptions) (*v1.OLMConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, oLMConfig *v1.OLMConfig, opts metav1.UpdateOptions) (*v1.OLMConfig, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.OLMConfig, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.OLMConfigList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.OLMConfig, err error)
	OLMConfigExpansion
}

// oLMConfigs implements OLMConfigInterface
type oLMConfigs struct {
	*gentype.ClientWithList[*v1.OLMConfig, *v1.OLMConfigList]
}

// newOLMConfigs returns a OLMConfigs
func newOLMConfigs(c *OperatorsV1Client) *oLMConfigs {
	return &oLMConfigs{
		gentype.NewClientWithList[*v1.OLMConfig, *v1.OLMConfigList](
			"olmconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1.OLMConfig { return &v1.OLMConfig{} },
			func() *v1.OLMConfigList { return &v1.OLMConfigList{} }),
	}
}
