/*
Copyright Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	availablev1alpha1 "github.com/operator-framework/operator-lifecycle-manager/pkg/available-csvs/apis/available/v1alpha1"
	versioned "github.com/operator-framework/operator-lifecycle-manager/pkg/available-csvs/client/clientset/versioned"
	internalinterfaces "github.com/operator-framework/operator-lifecycle-manager/pkg/available-csvs/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/operator-framework/operator-lifecycle-manager/pkg/available-csvs/client/listers/available/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AvailableClusterServiceVersionInformer provides access to a shared informer and lister for
// AvailableClusterServiceVersions.
type AvailableClusterServiceVersionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AvailableClusterServiceVersionLister
}

type availableClusterServiceVersionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAvailableClusterServiceVersionInformer constructs a new informer for AvailableClusterServiceVersion type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAvailableClusterServiceVersionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAvailableClusterServiceVersionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAvailableClusterServiceVersionInformer constructs a new informer for AvailableClusterServiceVersion type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAvailableClusterServiceVersionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AvailableV1alpha1().AvailableClusterServiceVersions(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AvailableV1alpha1().AvailableClusterServiceVersions(namespace).Watch(context.TODO(), options)
			},
		},
		&availablev1alpha1.AvailableClusterServiceVersion{},
		resyncPeriod,
		indexers,
	)
}

func (f *availableClusterServiceVersionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAvailableClusterServiceVersionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *availableClusterServiceVersionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&availablev1alpha1.AvailableClusterServiceVersion{}, f.defaultInformer)
}

func (f *availableClusterServiceVersionInformer) Lister() v1alpha1.AvailableClusterServiceVersionLister {
	return v1alpha1.NewAvailableClusterServiceVersionLister(f.Informer().GetIndexer())
}
