run:
  timeout: 8m

linters:
  enable:
  - gofmt
  - goimports
  - importas
  - misspell
  - stylecheck
  - tparallel
  - unconvert
  - whitespace
  disable:
  - errcheck

linters-settings:
  # This stanza is needed to avoid getting the warning
  # WARN [config_reader] The configuration option `linters.errcheck.ignore` is deprecated, please use `linters.errcheck.exclude-functions`.
  errcheck:
    ignore: ''

  importas:
    alias:
    - pkg: k8s.io/api/core/v1
      alias: corev1
    - pkg: k8s.io/api/apps/v1
      alias: appsv1
    - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
      alias: metav1
    - pkg: k8s.io/apimachinery/pkg/api/errors
      alias: apierrors
    - pkg: github.com/operator-framework/api/pkg/operators/v1alpha1
      alias: operatorsv1alpha1
    - pkg: github.com/operator-framework/api/pkg/operators/v1
      alias: operatorsv1
    - pkg: github.com/operator-framework/api/pkg/operators/v2
      alias: operatorsv2

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - pkg/lib
    - pkg/api
    - pkg/fakes
    - pkg/package-server/apis
    - test/e2e

output:
  formats: tab
  sort-results: true
