env:
- GO111MODULE=on
- CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
    - go mod vendor
builds:
  - id: olm
    main: ./cmd/olm
    binary: olm
    goos:
    - linux
    goarch:
    - amd64
    - arm64
    - ppc64le
    - s390x
    tags:
    - json1
    flags:
    - -mod=vendor
    ldflags:
    - -X {{ .Env.PKG }}/pkg/version.GitCommit={{ .FullCommit }}
    - -X {{ .Env.PKG }}/pkg/version.OLMVersion={{ .Tag }}
  - id: catalog
    main: ./cmd/catalog
    binary: catalog
    goos:
    - linux
    goarch:
    - amd64
    - arm64
    - ppc64le
    - s390x
    tags:
    - json1
    flags:
    - -mod=vendor
    ldflags:
    - -X {{ .Env.PKG }}/pkg/version.GitCommit={{ .FullCommit }}
    - -X {{ .Env.PKG }}/pkg/version.OLMVersion={{ .Tag }}
  - id: cpb
    main: ./util/cpb
    binary: cpb
    goos:
    - linux
    goarch:
    - amd64
    - arm64
    - ppc64le
    - s390x
    tags:
    - json1
    flags:
    - -mod=vendor
    ldflags:
    - -X {{ .Env.PKG }}/pkg/version.GitCommit={{ .FullCommit }}
    - -X {{ .Env.PKG }}/pkg/version.OLMVersion={{ .Tag }}
  - id: package-server
    main: ./cmd/package-server
    binary: package-server
    goos:
    - linux
    goarch:
    - amd64
    - arm64
    - ppc64le
    - s390x
    tags:
    - json1
    flags:
    - -mod=vendor
    ldflags:
    - -X {{ .Env.PKG }}/pkg/version.GitCommit={{ .FullCommit }}
    - -X {{ .Env.PKG }}/pkg/version.OLMVersion={{ .Tag }}
  - id: copy-content
    main: ./cmd/copy-content
    binary: copy-content
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    tags:
      - json1
    flags:
      - -mod=vendor
    ldflags:
      - -X {{ .Env.PKG }}/pkg/version.GitCommit={{ .FullCommit }}
      - -X {{ .Env.PKG }}/pkg/version.OLMVersion={{ .Tag }}
dockers:
- image_templates:
  - "{{ .Env.IMAGE_REPO }}:{{ .Tag }}-amd64"
  dockerfile: Dockerfile.goreleaser
  use: buildx
  goos: linux
  goarch: amd64
  build_flag_templates:
  - --platform=linux/amd64
- image_templates:
  - "{{ .Env.IMAGE_REPO }}:{{ .Tag }}-arm64"
  dockerfile: Dockerfile.goreleaser
  use: buildx
  goos: linux
  goarch: arm64
  build_flag_templates:
  - --platform=linux/arm64
- image_templates:
  - "{{ .Env.IMAGE_REPO }}:{{ .Tag }}-ppc64le"
  dockerfile: Dockerfile.goreleaser
  use: buildx
  goos: linux
  goarch: ppc64le
  build_flag_templates:
  - --platform=linux/ppc64le
- image_templates:
  - "{{ .Env.IMAGE_REPO }}:{{ .Tag }}-s390x"
  dockerfile: Dockerfile.goreleaser
  use: buildx
  goos: linux
  goarch: s390x
  build_flag_templates:
  - --platform=linux/s390x
docker_manifests:
- name_template: "{{ .Env.IMAGE_REPO }}:v{{ .Major }}.{{ .Minor }}"
  image_templates:
  - "{{ .Env.IMAGE_REPO }}:{{ .Tag }}-amd64"
  - "{{ .Env.IMAGE_REPO }}:{{ .Tag }}-arm64"
  - "{{ .Env.IMAGE_REPO }}:{{ .Tag }}-ppc64le"
  - "{{ .Env.IMAGE_REPO }}:{{ .Tag }}-s390x"
- name_template: "{{ .Env.IMAGE_REPO }}:{{ .Tag }}"
  image_templates:
  - "{{ .Env.IMAGE_REPO }}:{{ .Tag }}-amd64"
  - "{{ .Env.IMAGE_REPO }}:{{ .Tag }}-arm64"
  - "{{ .Env.IMAGE_REPO }}:{{ .Tag }}-ppc64le"
  - "{{ .Env.IMAGE_REPO }}:{{ .Tag }}-s390x"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^doc:'
      - '^test:'
release:
  draft: true
  header: |
    ## Install

    ### Scripted

    ```
    curl -L https://github.com/operator-framework/operator-lifecycle-manager/releases/download/{{ .Tag }}/install.sh -o install.sh
    chmod +x install.sh
    ./install.sh {{ .Tag }}
    ```
