FROM registry.centos.org/centos/centos:7

RUN yum update -y
RUN yum install -y golang make

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

WORKDIR /go/src/github.com/operator-framework/operator-lifecycle-manager
COPY . .

RUN make build
