# Update to quay.io address when new release made
FROM quay.io/coreos/tectonic-x-operator-dev:edcbca0f5088f3dd81de7417e7bb89bd34a266f9
LABEL maintainer="CoreOS Apps Team <team-apps@coreos.com>"
COPY manifests /manifests
