module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.23.0

toolchain go1.23.4

require sigs.k8s.io/controller-runtime/tools/setup-envtest v0.0.0-20250109154033-1de5a3e8bae9
