{{- if .Values.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.certManager.issuer.name }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.certManager.issuer.selfSigned }}
  selfSigned: {}
  {{- else if .Values.certManager.issuer.ca }}
  ca:
    secretName: {{ .Values.certManager.issuer.ca.secretName }}
  {{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.certificate.name }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.certManager.certificate.secretName }}
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - localhost
    - catalog-operator.{{ .Values.namespace }}.svc
    - catalog-operator.{{ .Values.namespace }}.svc.cluster.local
    - olm-operator.{{ .Values.namespace }}.svc
    - olm-operator.{{ .Values.namespace }}.svc.cluster.local
    {{- range .Values.certManager.certificate.extraDnsNames }}
    - {{ . }}
    {{- end }}
  ipAddresses:
    - 127.0.0.1
    {{- range .Values.certManager.certificate.extraIpAddresses }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: {{ .Values.certManager.issuer.name }}
    kind: Issuer
    group: cert-manager.io
{{- end }}

