apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels: 
    {{- if .Values.namespace_psa }}
    pod-security.kubernetes.io/enforce: {{ .Values.namespace_psa.enforceLevel }}
    pod-security.kubernetes.io/enforce-version: {{ .Values.namespace_psa.enforceVersion }}
    {{- end }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operator_namespace }}
  labels:
    {{- if .Values.operator_namespace_psa }}
    pod-security.kubernetes.io/enforce: {{ .Values.operator_namespace_psa.enforceLevel }}
    pod-security.kubernetes.io/enforce-version: {{ .Values.operator_namespace_psa.enforceVersion }}
    {{- end }}
