{{- if .Values.imagestream }}
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: {{ .Values.writeStatusName }}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
  relatedObjects:
    - group: operators.coreos.com
      name: packageserver
      namespace: openshift-operator-lifecycle-manager
      resource: clusterserviceversions
---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: {{ .Values.writeStatusNameCatalog }}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
  relatedObjects:
    - group: ""
      name: openshift-operator-lifecycle-manager
      resource: namespaces
{{- if .Values.writePackageServerStatusName }}
---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: {{ .Values.writePackageServerStatusName }}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
  relatedObjects:
    - group: ""
      name: openshift-operator-lifecycle-manager
      resource: namespaces
    - group: operators.coreos.com
      name: packageserver
      namespace: openshift-operator-lifecycle-manager
      resource: clusterserviceversions
{{- end }}      
{{- end }}
