apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alm-operator
  namespace: {{ .Values.namespace }}
  labels:
    app: alm-operator
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.alm.replicaCount }}
  selector:
    matchLabels:
      app: alm-operator
  template:
    metadata:
      labels:
        app: alm-operator
    spec:
      serviceAccountName: alm-operator-serviceaccount
      containers:
        - name: alm-operator
          command:
          - /bin/alm
          {{- if .Values.watchedNamespaces }}
          - -watchedNamespaces
          - {{ .Values.watchedNamespaces }}
          {{- end }}
          {{- if .Values.alm.commandArgs }}
          - {{ .Values.alm.commandArgs }}
          {{- end }}
          image: {{ .Values.alm.image.ref }}
          imagePullPolicy: {{ .Values.alm.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.alm.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.alm.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.alm.service.internalPort }}
          env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPERATOR_NAME
            value: alm-operator
          {{- if .Values.alm.resources }}
          resources:
{{ toYaml .Values.alm.resources | indent 12 }}
          {{- end}}
    {{- if .Values.alm.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.alm.nodeSelector | indent 8 }}
    {{- end }}
      imagePullSecrets:
        - name: coreos-pull-secret
