apiVersion: v1
kind: Secret
metadata:
  name: almservicebroker-client
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: alm-operator-serviceaccount
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
type: kubernetes.io/service-account-token
