/*
Copyright Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"context"

	operators "github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/apis/operators"
	scheme "github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/client/clientset/internalversion/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PackageManifestsGetter has a method to return a PackageManifestInterface.
// A group's client should implement this interface.
type PackageManifestsGetter interface {
	PackageManifests(namespace string) PackageManifestInterface
}

// PackageManifestInterface has methods to work with PackageManifest resources.
type PackageManifestInterface interface {
	Create(ctx context.Context, packageManifest *operators.PackageManifest, opts v1.CreateOptions) (*operators.PackageManifest, error)
	Update(ctx context.Context, packageManifest *operators.PackageManifest, opts v1.UpdateOptions) (*operators.PackageManifest, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, packageManifest *operators.PackageManifest, opts v1.UpdateOptions) (*operators.PackageManifest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*operators.PackageManifest, error)
	List(ctx context.Context, opts v1.ListOptions) (*operators.PackageManifestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operators.PackageManifest, err error)
	PackageManifestExpansion
}

// packageManifests implements PackageManifestInterface
type packageManifests struct {
	*gentype.ClientWithList[*operators.PackageManifest, *operators.PackageManifestList]
}

// newPackageManifests returns a PackageManifests
func newPackageManifests(c *PackagesClient, namespace string) *packageManifests {
	return &packageManifests{
		gentype.NewClientWithList[*operators.PackageManifest, *operators.PackageManifestList](
			"packagemanifests",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *operators.PackageManifest { return &operators.PackageManifest{} },
			func() *operators.PackageManifestList { return &operators.PackageManifestList{} }),
	}
}
