/*
Copyright Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	operatorsv1alpha1 "github.com/operator-framework/api/pkg/operators/v1alpha1"
	scheme "github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterServiceVersionsGetter has a method to return a ClusterServiceVersionInterface.
// A group's client should implement this interface.
type ClusterServiceVersionsGetter interface {
	ClusterServiceVersions(namespace string) ClusterServiceVersionInterface
}

// ClusterServiceVersionInterface has methods to work with ClusterServiceVersion resources.
type ClusterServiceVersionInterface interface {
	Create(ctx context.Context, clusterServiceVersion *operatorsv1alpha1.ClusterServiceVersion, opts v1.CreateOptions) (*operatorsv1alpha1.ClusterServiceVersion, error)
	Update(ctx context.Context, clusterServiceVersion *operatorsv1alpha1.ClusterServiceVersion, opts v1.UpdateOptions) (*operatorsv1alpha1.ClusterServiceVersion, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterServiceVersion *operatorsv1alpha1.ClusterServiceVersion, opts v1.UpdateOptions) (*operatorsv1alpha1.ClusterServiceVersion, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*operatorsv1alpha1.ClusterServiceVersion, error)
	List(ctx context.Context, opts v1.ListOptions) (*operatorsv1alpha1.ClusterServiceVersionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operatorsv1alpha1.ClusterServiceVersion, err error)
	ClusterServiceVersionExpansion
}

// clusterServiceVersions implements ClusterServiceVersionInterface
type clusterServiceVersions struct {
	*gentype.ClientWithList[*operatorsv1alpha1.ClusterServiceVersion, *operatorsv1alpha1.ClusterServiceVersionList]
}

// newClusterServiceVersions returns a ClusterServiceVersions
func newClusterServiceVersions(c *OperatorsV1alpha1Client, namespace string) *clusterServiceVersions {
	return &clusterServiceVersions{
		gentype.NewClientWithList[*operatorsv1alpha1.ClusterServiceVersion, *operatorsv1alpha1.ClusterServiceVersionList](
			"clusterserviceversions",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *operatorsv1alpha1.ClusterServiceVersion { return &operatorsv1alpha1.ClusterServiceVersion{} },
			func() *operatorsv1alpha1.ClusterServiceVersionList {
				return &operatorsv1alpha1.ClusterServiceVersionList{}
			},
		),
	}
}
