/*
Copyright Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/operator-framework/api/pkg/operators/v1alpha1"
	scheme "github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InstallPlansGetter has a method to return a InstallPlanInterface.
// A group's client should implement this interface.
type InstallPlansGetter interface {
	InstallPlans(namespace string) InstallPlanInterface
}

// InstallPlanInterface has methods to work with InstallPlan resources.
type InstallPlanInterface interface {
	Create(ctx context.Context, installPlan *v1alpha1.InstallPlan, opts v1.CreateOptions) (*v1alpha1.InstallPlan, error)
	Update(ctx context.Context, installPlan *v1alpha1.InstallPlan, opts v1.UpdateOptions) (*v1alpha1.InstallPlan, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, installPlan *v1alpha1.InstallPlan, opts v1.UpdateOptions) (*v1alpha1.InstallPlan, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.InstallPlan, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.InstallPlanList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InstallPlan, err error)
	InstallPlanExpansion
}

// installPlans implements InstallPlanInterface
type installPlans struct {
	*gentype.ClientWithList[*v1alpha1.InstallPlan, *v1alpha1.InstallPlanList]
}

// newInstallPlans returns a InstallPlans
func newInstallPlans(c *OperatorsV1alpha1Client, namespace string) *installPlans {
	return &installPlans{
		gentype.NewClientWithList[*v1alpha1.InstallPlan, *v1alpha1.InstallPlanList](
			"installplans",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.InstallPlan { return &v1alpha1.InstallPlan{} },
			func() *v1alpha1.InstallPlanList { return &v1alpha1.InstallPlanList{} }),
	}
}
