// +build !ignore_autogenerated

/*
Copyright Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&AvailableClusterServiceVersion{}, func(obj interface{}) {
		SetObjectDefaults_AvailableClusterServiceVersion(obj.(*AvailableClusterServiceVersion))
	})
	scheme.AddTypeDefaultingFunc(&AvailableClusterServiceVersionList{}, func(obj interface{}) {
		SetObjectDefaults_AvailableClusterServiceVersionList(obj.(*AvailableClusterServiceVersionList))
	})
	return nil
}

func SetObjectDefaults_AvailableClusterServiceVersion(in *AvailableClusterServiceVersion) {
	for i := range in.Spec.ClusterServiceVersionSpec.InstallStrategy.StrategySpec.DeploymentSpecs {
		a := &in.Spec.ClusterServiceVersionSpec.InstallStrategy.StrategySpec.DeploymentSpecs[i]
		for j := range a.Spec.Template.Spec.InitContainers {
			b := &a.Spec.Template.Spec.InitContainers[j]
			for k := range b.Ports {
				c := &b.Ports[k]
				if c.Protocol == "" {
					c.Protocol = "TCP"
				}
			}
		}
		for j := range a.Spec.Template.Spec.Containers {
			b := &a.Spec.Template.Spec.Containers[j]
			for k := range b.Ports {
				c := &b.Ports[k]
				if c.Protocol == "" {
					c.Protocol = "TCP"
				}
			}
		}
		for j := range a.Spec.Template.Spec.EphemeralContainers {
			b := &a.Spec.Template.Spec.EphemeralContainers[j]
			for k := range b.EphemeralContainerCommon.Ports {
				c := &b.EphemeralContainerCommon.Ports[k]
				if c.Protocol == "" {
					c.Protocol = "TCP"
				}
			}
		}
	}
}

func SetObjectDefaults_AvailableClusterServiceVersionList(in *AvailableClusterServiceVersionList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_AvailableClusterServiceVersion(a)
	}
}
