##---
# Source: olm/templates/30_13-packageserver.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.packages.apps.redhat.com
spec:
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQWQyZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFjTVJvd0dBWURWUVFERXhGd1lXTnIKWVdkbExYTmxjblpsY2kxallUQWVGdzB4T0RBNU1qWXhPVFUyTXpoYUZ3MHlPREE1TWpNeE9UVTJNemhhTUJ3eApHakFZQmdOVkJBTVRFWEJoWTJ0aFoyVXRjMlZ5ZG1WeUxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUF2cGFKOUF2Z2kwRmM5V0w1OXJLNzl1c2xaSTAyRjkzQ3pkQWVUTURjdDRScU1uL2QKdkY4MHFRbVgrTVpFQi9lelZlV25KaFBzeG9Ib3ZwWWVzSXRLdkYvcmYwZlFWb1RUT3NvS2lvNTRtdWNlM09HbwpOMEFqdEhyRFhGNUlObDJNVTVLeUxab3dxcFRQZFJoamNWdUswQmwrQllqaGxSOXdyTTA2MHQvV1FOMEZtbzNkCkxQR2dhcDh0NjNlcVhoYm14SXpaSVNQamdBVmxkeVhYUkZ4cktpbmtsM1o2ZzN0eFhMaWxJaUczblF4dUNFM3QKRmVyTnlIWVhGTG9pSEVtbjdZcmJlak1Ja0pWSEl4SVJKcXkvMTFKM1V4WXl0SEYvNlIxdmlpQnpFOTc4SS95NQpnendRNHV1OUZ0Q1VZcXZLemRsSDZCMHU2bVREc3VhSnVvN25KUUlEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUYKTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSVNIaDFnK0Z1R3dad2RERnhxRFNEclgrSDQxYS9EaAowRnRoUEdUUHNaTnY4OXJCdldUT0xsSDlONldYaTZTRE54Zno3em5YcjVlT25TSisvQk5pcENBTzBwY0lqdW1QCmlSSDdCRzhTWU1BVVZSUTliVWRtZ1JkV3lTOC8rT3RpOTdKczhhWUlQRDM2TzVUODF3ekh2ajloQThhc3EvU28KVlc0UmEyT1FKSmVmUk5oWVlmWW80amVnUFVidWRENzM2S1paUXNJeEQ2S0lTdllQa0RKTG1uM1BpOG9GZllCMApjYkQvV2dxRkZlUWNhamVMU2hGQllZQWFxY3VJamx5VFY2RkcxUTJSY2tPaWRNR2RJcmRnKzlubmVJeTFCeGo1CjNhck1VMWFIZVZQM0U3bnNVRHpqZjVieUJxdHJ3OXJKNVgyWFhCb0w5bjVpa24wK3ZzNkUwNVU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  group: packages.apps.redhat.com
  groupPriorityMinimum: 2000
  versionPriority: 15
  service:
    name: package-server
    namespace: openshift-operator-lifecycle-manager
  version: v1alpha1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packagemanifest:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: openshift-operator-lifecycle-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: packagemanifest-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: openshift-operator-lifecycle-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packagemanifest-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: openshift-operator-lifecycle-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: package-apiserver-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregated-apiserver-clusterrole
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: openshift-operator-lifecycle-manager
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: package-server-certs
  namespace: openshift-operator-lifecycle-manager
  labels:
    app: package-server
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhakNDQWxLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFjTVJvd0dBWURWUVFERXhGd1lXTnIKWVdkbExYTmxjblpsY2kxallUQWVGdzB4T0RBNU1qWXhPVFUyTXpoYUZ3MHhPVEE1TWpZeE9UVTJNemhhTUJreApGekFWQmdOVkJBTVREbkJoWTJ0aFoyVXRjMlZ5ZG1WeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQTRHMG44U0czZ2FUcVpFbnhHMjZ3UmdRMVRMS05xcHBiRzREN1EvRTZIWmFtRkdnTjBISTUKY1ZJVm1YTlVTUGtvTytDYjRhY0NDKzJueUxSNFI5VFh5Ri9FSHAvc0ZpcXl0QW50ZWRRazZSZ0I4WXZISWsxKwpDL3FBY1RKMmluOHI0SzlyQytHemRCU0NXNlhETFF4NlVnNHQ5UUp5aSt3MEZ3cGduMFlBS2NoSDJaZGxnOWpGCnppN29IOEg4SWNlUnNxdDRqNXI4YjZrS0ZwUElEM0dER3F6YlZrWmEwdGdNTEcyN21ibE1RMWZZN0gvMWk4azgKMm1FRDV4Q2tneFgySEZ1UDZWdUFuVWdtcnJBcW9sUk84ak5yR0RLUWtLVnFUenpsbFlPVnFWTExXaGpxckFXLwpIYWFHNTZGdXJnT0pXcGJMQi9tSGtoYjlzZ2VieUU3OER3SURBUUFCbzRHNU1JRzJNQTRHQTFVZER3RUIvd1FFCkF3SUZvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXcKQURCM0JnTlZIUkVFY0RCdWdqTndZV05yWVdkbExYTmxjblpsY2k1dmNHVnVjMmhwWm5RdGIzQmxjbUYwYjNJdApiR2xtWldONVkyeGxMVzFoYm1GblpYS0NOM0JoWTJ0aFoyVXRjMlZ5ZG1WeUxtOXdaVzV6YUdsbWRDMXZjR1Z5CllYUnZjaTFzYVdabFkzbGpiR1V0YldGdVlXZGxjaTV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHOCsKSk5uU3VBVHkyQ1FRZmlaOThFRVBXM0s0di8yaktjRWY1QlhFaWFITXJQaXVXcEpvRzNRT1BLL25wOUdQem80UwpPS2JQY0ttcDJNcFpCY01QQ3VGWkJEZ24wdWt2bmtCb3JiN09vWUduem9Bd0RtRDlIMkJ6ejBYKzREOTM4a3B5CmVXelpNT0h2ekNUYTJYTzVTSTBlT2NPcy83c3Q5SVBjcEdncjdzdGJQQ05GSlk2Zmlia1JYWU9sdkNheWlPRmcKd2NKVVloQ0l6WUdHbUtheS8rQ2l4QlRVQWt0enRHYmcxVmxYZHFnL281UC9uVTJWUU5CZHE1YWR1WjRpVmZ2dwpmenB0SnE4RW9ZT0V6TXE2OVZGM1VIbWJFakluSDRHa01IcEUrQ25KYVJIRExWMVlnWmlFWmlSK0FDSUZMa3pXCnZFQUdqTUZ2SGpYQkJSemVwU2c9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  tls.key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBNEcwbjhTRzNnYVRxWkVueEcyNndSZ1ExVExLTnFwcGJHNEQ3US9FNkhaYW1GR2dOCjBISTVjVklWbVhOVVNQa29PK0NiNGFjQ0MrMm55TFI0UjlUWHlGL0VIcC9zRmlxeXRBbnRlZFFrNlJnQjhZdkgKSWsxK0MvcUFjVEoyaW44cjRLOXJDK0d6ZEJTQ1c2WERMUXg2VWc0dDlRSnlpK3cwRndwZ24wWUFLY2hIMlpkbApnOWpGemk3b0g4SDhJY2VSc3F0NGo1cjhiNmtLRnBQSUQzR0RHcXpiVmtaYTB0Z01MRzI3bWJsTVExZlk3SC8xCmk4azgybUVENXhDa2d4WDJIRnVQNlZ1QW5VZ21yckFxb2xSTzhqTnJHREtRa0tWcVR6emxsWU9WcVZMTFdoanEKckFXL0hhYUc1NkZ1cmdPSldwYkxCL21Ia2hiOXNnZWJ5RTc4RHdJREFRQUJBb0lCQUV0cWd2eVY3dnVpOXAwaQo5K0hYRFdkSjdMdE1XU3pXVi8xakY0eWFXSVF1NXJwK3lQMmVGTTJPM3ZGRS96TFNmNEczbGNwN2U4V1VaRWllCjFMaVd2cmgzN2dpNGh2WmYvTk5oYnFyODdqWmlPZXo0b3I5Vk9TRS9XY0F3VEFONGZyOHZVNUtYa3QxVU13WW4KS3ZKTmVpRnU0R1N3SU53Q1VQTFpLdVQ2K2YwUHpqa0VMY1pTTTRubmU5LzExSHMveTRNOFp2UUNZV25RNDB5RQo3R2xyNkw5Y1hEWldhdzZZcnJDdEhVc1VnVHozc2RyL3o2bTBROXQxcXJiYlBhZHBXYUg3NmdmWE5vS1ZiVm83ClZ2Zk05ditvTjhqU0c5QnUzOUc4SzBuUWhqRm9kN0ZhcWN4d0p3Vi95WnRiOWJSL3IzcCswdERoVTRZUWVheXUKMEI5dkZQa0NnWUVBNHlGY2NLSHVXM1dlODhuZVp4c3VQRE8xSEJJSkhJM0lEbGNVYXlqa29XcStSNjZFNStwUAp4OGFxR0Y1Z084czV5YlZKRld6MzhsclJJSjhiRlNLdFpRakN6ZzlOY2Zzd2E3K3hTMkR5UkpsZTV3R2dYQW5yCjJNVWlmbDlyY1NjdXpSNEk4OXJJalVoYS9TR0RjMWZZWHZGWEsxenRCdkY4VFJ1bnMzQ2EzT1VDZ1lFQS9QUFAKczlEaThWTTNCU21GMXVCQ1ZGczkvTXVUZGs4WXIyNHNCS0pLQ2xoNFdoV0hBbVc5WFAxOFZjY0cycTJ4dGxReQppQzFmTkZpQ24yREVDKzhlYlU0U1hwdHJ1NHV4amR2ZG4rRHFGNjh5RFFWYlhjd3I2YmF4bVZqQ2g3dkJEdXJjCjlJK2g3N1VFVUw1cVVUWC8rR25Oa0RZZWh1TmxvTmlzYUtYVDJlTUNnWUFJZDNibHIvT2RyeTNFc3JLNnJ6V3oKQXM1dWhIR1lnZVNDUEZiRGc5dTU5S3V4S2wxRDgrVVRjbUZtMVNYTE5ORXJwcmxadGgwc0NKeWhGYTFCeFhBbgpRd05ZQVJRRytyRWNZeUh0eUdoZmpFUVFZbXdpNGkvTGZkWENWalpBR3BEUkRweVEwb2dGVkR3b0VYYS85dmRXCjJySkFLSStoWWFFYmtydFdvZ3p6elFLQmdEYlhvYU9wMlZwYklXVzBIL2w3ZThZUVZqczE1QTNWamxPU3ZtWnUKelVDNjk3VUlUOUk4UHJjbm1rcDZzVWkrT2ZaL0FNbTNsSm1qeXdaRkU1eEd4c0VLR1Q5NzBQckRpY1pvOGY4VQo0NHdwQnQvOTFsWmF5dmFNRHF0aHJDT0RtSkxrWnUxN0txL3UvaldIWTBPaVFwSVlWbUk2Nlpsek9maUtvYTY2CnJWampBb0dBT1E3eWkyVndjcWxZdm1FdG0rcGdiUFZ0dXIxTnNHZGF0TnFUbHc4QVdmd28wM011NlREcGJvcloKeHNySjEwbkVCUmtXekgvUGc1ckdkZ01JY0FSVitwSzd4K1kyOElCR1BtbUI5VDVBaWN6V0NaaTBOSXlQK05jZQpkTSsvSkhBQ0NTakxEblFTSzErZVhrcmZ1TkNsbktydEtVNjlpOWxIbmN1d1NnOUIyd2c9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: package-server
  namespace: openshift-operator-lifecycle-manager
  labels:
    app: package-server
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: package-server
  template:
    metadata:
      labels:
        app: package-server
    spec:
      serviceAccountName: olm-operator-serviceaccount
      containers:
      - name: package-server
        command:
        - /bin/package-server
        - -v=4
        - --debug
        image: quay.io/coreos/package-server@sha256:cc18b5711fb2126329c969f077f67f41981c87f800f6b2ceae5981422c14917b
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        volumeMounts:
        - name: certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 443
        readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 443
      volumes:
      - name: certs
        secret:
          secretName: package-server-certs
          items:
          - key: tls.crt
            path: apiserver.crt
          - key: tls.key
            path: apiserver.key
      imagePullSecrets:
        - name: coreos-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: package-server
  namespace: openshift-operator-lifecycle-manager
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: package-server
