##---
# Source: olm/templates/30_08-certified-operators.catalogsource.yaml

#! validate-crd: ./deploy/chart/templates/05-catalogsource.crd.yaml
#! parse-kind: CatalogSource
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: certified-operators
  namespace: openshift-operator-lifecycle-manager
spec:
  sourceType: internal
  configMap: certified-operators
  displayName: Certified Operators
  publisher: Red Hat

