apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-alm
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.alm.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-alm
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "fullname" . }}-serviceaccount
      containers:
        - name: {{ .Chart.Name }}
          command:
          - /bin/alm
          - -watchedNamespaces
          - {{ .Values.namespace }}
          image: "{{ .Values.alm.image.repository }}:{{ .Values.alm.image.tag }}"
          imagePullPolicy: {{ .Values.alm.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.alm.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.alm.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.alm.service.internalPort }}
          env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPERATOR_NAME
            value: {{ template "fullname" . }}-alm
          resources:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      imagePullSecrets:
        - name: coreos-pull-secret
