apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: installplan-v1s.app.coreos.com
  annotations:
    displayName: Install Plan
    description: Represents a plan to install and resolve dependencies for Cluster Services
spec:
  group: app.coreos.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: installplan-v1s
    singular: installplan-v1
    kind: InstallPlan-v1
    listKind: InstallPlanList-v1
  validation:
    openAPIV3Schema:
      type: object
      description: Document which defines the desire and current state of an installation of a Cluster Service
      required:
      - clusterServiceVersionNames
      - approval
      properties:
        clusterServiceVersionNames:
          type: array
          description: A list of the names of the Cluster Services
          items:
            type: string
        approval:
          type: string
          enum:
          - Automatic
          - Manual
          - Update-Only # Will only apply an update if it updates existing packages only and doesn't add any new ones
        serviceAccountName:
          type: string
          description: The serviceaccount to use to create resources. If not specified, the default serviceaccount for the namespace will be used.

# Schema for status key written by the operator:
#status:
# type: object
# required:
# - status
# properties:
#   status:
#     type: string
#     enum:
#     - Planning
#     - Requires Approval
#     - Installing
#     - Complete
#   plan:
#     type: array
#     items:
#       type: object
#       required:
#       - resolving
#       - resource
#       - status
#       properties:
#         resolving:
#           type: string
#         status:
#           type: string
#           enum:
#           - Unknown
#           - Not Present
#           - Present
#           - Created
#         resource:
#           type: object
#           required:
#           - group
#           - version
#           - kind
#           - name
#           - manifest
#           properties:
#             group:
#               type: string
#             version:
#               type: string
#             kind:
#               type: string
#             name:
#               type: string
#             manifest:
#               type: string
