##---
# Source: olm/templates/0000_30_13-packageserver.subscription.yaml
#! validate-crd: ./deploy/chart/templates/04-subscription.crd.yaml
#! parse-kind: Subscription
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: packageserver
  namespace: olm
spec:
  source: olm-operators
  sourceNamespace: olm
  name: packageserver
  channel: alpha
