---
# Source: olm/templates/0000_30_00-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: olm
  labels:
    openshift.io/run-level: "1"
    olm.components: "global"
---
apiVersion: v1
kind: Namespace
metadata:
  name: operators
  labels:
    openshift.io/run-level: "1"
