// +build !ignore_autogenerated

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1alpha1

import (
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	reflect "reflect"
)

// GetGeneratedDeepCopyFuncs returns the generated funcs, since we aren't registering them.
//
// Deprecated: deepcopy registration will go away when static deepcopy is fully implemented.
func GetGeneratedDeepCopyFuncs() []conversion.GeneratedDeepCopyFunc {
	return []conversion.GeneratedDeepCopyFunc{
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*InstallPlan).DeepCopyInto(out.(*InstallPlan))
			return nil
		}, InType: reflect.TypeOf(&InstallPlan{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*InstallPlanCondition).DeepCopyInto(out.(*InstallPlanCondition))
			return nil
		}, InType: reflect.TypeOf(&InstallPlanCondition{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*InstallPlanList).DeepCopyInto(out.(*InstallPlanList))
			return nil
		}, InType: reflect.TypeOf(&InstallPlanList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*InstallPlanSpec).DeepCopyInto(out.(*InstallPlanSpec))
			return nil
		}, InType: reflect.TypeOf(&InstallPlanSpec{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*InstallPlanStatus).DeepCopyInto(out.(*InstallPlanStatus))
			return nil
		}, InType: reflect.TypeOf(&InstallPlanStatus{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*Step).DeepCopyInto(out.(*Step))
			return nil
		}, InType: reflect.TypeOf(&Step{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*StepResource).DeepCopyInto(out.(*StepResource))
			return nil
		}, InType: reflect.TypeOf(&StepResource{})},
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallPlan) DeepCopyInto(out *InstallPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallPlan.
func (in *InstallPlan) DeepCopy() *InstallPlan {
	if in == nil {
		return nil
	}
	out := new(InstallPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstallPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallPlanCondition) DeepCopyInto(out *InstallPlanCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallPlanCondition.
func (in *InstallPlanCondition) DeepCopy() *InstallPlanCondition {
	if in == nil {
		return nil
	}
	out := new(InstallPlanCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallPlanList) DeepCopyInto(out *InstallPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstallPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallPlanList.
func (in *InstallPlanList) DeepCopy() *InstallPlanList {
	if in == nil {
		return nil
	}
	out := new(InstallPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstallPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallPlanSpec) DeepCopyInto(out *InstallPlanSpec) {
	*out = *in
	if in.ClusterServiceVersionNames != nil {
		in, out := &in.ClusterServiceVersionNames, &out.ClusterServiceVersionNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallPlanSpec.
func (in *InstallPlanSpec) DeepCopy() *InstallPlanSpec {
	if in == nil {
		return nil
	}
	out := new(InstallPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallPlanStatus) DeepCopyInto(out *InstallPlanStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]InstallPlanCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = make([]Step, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallPlanStatus.
func (in *InstallPlanStatus) DeepCopy() *InstallPlanStatus {
	if in == nil {
		return nil
	}
	out := new(InstallPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Step) DeepCopyInto(out *Step) {
	*out = *in
	out.Resource = in.Resource
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Step.
func (in *Step) DeepCopy() *Step {
	if in == nil {
		return nil
	}
	out := new(Step)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepResource) DeepCopyInto(out *StepResource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepResource.
func (in *StepResource) DeepCopy() *StepResource {
	if in == nil {
		return nil
	}
	out := new(StepResource)
	in.DeepCopyInto(out)
	return out
}
