/*
Copyright Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/operator-framework/operator-lifecycle-manager/pkg/available-csvs/apis/available/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAvailableClusterServiceVersions implements AvailableClusterServiceVersionInterface
type FakeAvailableClusterServiceVersions struct {
	Fake *FakeAvailableV1alpha1
	ns   string
}

var availableclusterserviceversionsResource = schema.GroupVersionResource{Group: "available.operators.coreos.com", Version: "v1alpha1", Resource: "availableclusterserviceversions"}

var availableclusterserviceversionsKind = schema.GroupVersionKind{Group: "available.operators.coreos.com", Version: "v1alpha1", Kind: "AvailableClusterServiceVersion"}

// Get takes name of the availableClusterServiceVersion, and returns the corresponding availableClusterServiceVersion object, and an error if there is any.
func (c *FakeAvailableClusterServiceVersions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AvailableClusterServiceVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(availableclusterserviceversionsResource, c.ns, name), &v1alpha1.AvailableClusterServiceVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AvailableClusterServiceVersion), err
}

// List takes label and field selectors, and returns the list of AvailableClusterServiceVersions that match those selectors.
func (c *FakeAvailableClusterServiceVersions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AvailableClusterServiceVersionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(availableclusterserviceversionsResource, availableclusterserviceversionsKind, c.ns, opts), &v1alpha1.AvailableClusterServiceVersionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AvailableClusterServiceVersionList{ListMeta: obj.(*v1alpha1.AvailableClusterServiceVersionList).ListMeta}
	for _, item := range obj.(*v1alpha1.AvailableClusterServiceVersionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested availableClusterServiceVersions.
func (c *FakeAvailableClusterServiceVersions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(availableclusterserviceversionsResource, c.ns, opts))

}

// Create takes the representation of a availableClusterServiceVersion and creates it.  Returns the server's representation of the availableClusterServiceVersion, and an error, if there is any.
func (c *FakeAvailableClusterServiceVersions) Create(ctx context.Context, availableClusterServiceVersion *v1alpha1.AvailableClusterServiceVersion, opts v1.CreateOptions) (result *v1alpha1.AvailableClusterServiceVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(availableclusterserviceversionsResource, c.ns, availableClusterServiceVersion), &v1alpha1.AvailableClusterServiceVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AvailableClusterServiceVersion), err
}

// Update takes the representation of a availableClusterServiceVersion and updates it. Returns the server's representation of the availableClusterServiceVersion, and an error, if there is any.
func (c *FakeAvailableClusterServiceVersions) Update(ctx context.Context, availableClusterServiceVersion *v1alpha1.AvailableClusterServiceVersion, opts v1.UpdateOptions) (result *v1alpha1.AvailableClusterServiceVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(availableclusterserviceversionsResource, c.ns, availableClusterServiceVersion), &v1alpha1.AvailableClusterServiceVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AvailableClusterServiceVersion), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAvailableClusterServiceVersions) UpdateStatus(ctx context.Context, availableClusterServiceVersion *v1alpha1.AvailableClusterServiceVersion, opts v1.UpdateOptions) (*v1alpha1.AvailableClusterServiceVersion, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(availableclusterserviceversionsResource, "status", c.ns, availableClusterServiceVersion), &v1alpha1.AvailableClusterServiceVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AvailableClusterServiceVersion), err
}

// Delete takes name of the availableClusterServiceVersion and deletes it. Returns an error if one occurs.
func (c *FakeAvailableClusterServiceVersions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(availableclusterserviceversionsResource, c.ns, name), &v1alpha1.AvailableClusterServiceVersion{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAvailableClusterServiceVersions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(availableclusterserviceversionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AvailableClusterServiceVersionList{})
	return err
}

// Patch applies the patch and returns the patched availableClusterServiceVersion.
func (c *FakeAvailableClusterServiceVersions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AvailableClusterServiceVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(availableclusterserviceversionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AvailableClusterServiceVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AvailableClusterServiceVersion), err
}
