// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/client/uicatalogentry_client.go

// Package catalog is a generated GoMock package.
package catalog

import (
	v1alpha1 "github.com/coreos-inc/alm/pkg/apis/uicatalogentry/v1alpha1"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUICatalogEntryInterface is a mock of UICatalogEntryInterface interface
type MockUICatalogEntryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUICatalogEntryInterfaceMockRecorder
}

// MockUICatalogEntryInterfaceMockRecorder is the mock recorder for MockUICatalogEntryInterface
type MockUICatalogEntryInterfaceMockRecorder struct {
	mock *MockUICatalogEntryInterface
}

// NewMockUICatalogEntryInterface creates a new mock instance
func NewMockUICatalogEntryInterface(ctrl *gomock.Controller) *MockUICatalogEntryInterface {
	mock := &MockUICatalogEntryInterface{ctrl: ctrl}
	mock.recorder = &MockUICatalogEntryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUICatalogEntryInterface) EXPECT() *MockUICatalogEntryInterfaceMockRecorder {
	return m.recorder
}

// UpdateEntry mocks base method
func (m *MockUICatalogEntryInterface) UpdateEntry(csv *v1alpha1.UICatalogEntry) (*v1alpha1.UICatalogEntry, error) {
	ret := m.ctrl.Call(m, "UpdateEntry", csv)
	ret0, _ := ret[0].(*v1alpha1.UICatalogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEntry indicates an expected call of UpdateEntry
func (mr *MockUICatalogEntryInterfaceMockRecorder) UpdateEntry(csv interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEntry", reflect.TypeOf((*MockUICatalogEntryInterface)(nil).UpdateEntry), csv)
}
