apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reportdatasources.chargeback.coreos.com
spec:
  group: chargeback.coreos.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: reportdatasources
    singular: reportdatasource
    kind: ReportDataSource
