/*
Copyright Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	context "context"

	operatorsv2 "github.com/operator-framework/api/pkg/operators/v2"
	scheme "github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OperatorConditionsGetter has a method to return a OperatorConditionInterface.
// A group's client should implement this interface.
type OperatorConditionsGetter interface {
	OperatorConditions(namespace string) OperatorConditionInterface
}

// OperatorConditionInterface has methods to work with OperatorCondition resources.
type OperatorConditionInterface interface {
	Create(ctx context.Context, operatorCondition *operatorsv2.OperatorCondition, opts v1.CreateOptions) (*operatorsv2.OperatorCondition, error)
	Update(ctx context.Context, operatorCondition *operatorsv2.OperatorCondition, opts v1.UpdateOptions) (*operatorsv2.OperatorCondition, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, operatorCondition *operatorsv2.OperatorCondition, opts v1.UpdateOptions) (*operatorsv2.OperatorCondition, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*operatorsv2.OperatorCondition, error)
	List(ctx context.Context, opts v1.ListOptions) (*operatorsv2.OperatorConditionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operatorsv2.OperatorCondition, err error)
	OperatorConditionExpansion
}

// operatorConditions implements OperatorConditionInterface
type operatorConditions struct {
	*gentype.ClientWithList[*operatorsv2.OperatorCondition, *operatorsv2.OperatorConditionList]
}

// newOperatorConditions returns a OperatorConditions
func newOperatorConditions(c *OperatorsV2Client, namespace string) *operatorConditions {
	return &operatorConditions{
		gentype.NewClientWithList[*operatorsv2.OperatorCondition, *operatorsv2.OperatorConditionList](
			"operatorconditions",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *operatorsv2.OperatorCondition { return &operatorsv2.OperatorCondition{} },
			func() *operatorsv2.OperatorConditionList { return &operatorsv2.OperatorConditionList{} },
		),
	}
}
