// Code generated by counterfeiter. DO NOT EDIT.
package operatorlisterfakes

import (
	"sync"

	"github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorlister"
	"k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1"
)

type FakeAPIRegistrationV1Lister struct {
	APIServiceListerStub        func() v1.APIServiceLister
	aPIServiceListerMutex       sync.RWMutex
	aPIServiceListerArgsForCall []struct{}
	aPIServiceListerReturns     struct {
		result1 v1.APIServiceLister
	}
	aPIServiceListerReturnsOnCall map[int]struct {
		result1 v1.APIServiceLister
	}
	RegisterAPIServiceListerStub        func(v1.APIServiceLister)
	registerAPIServiceListerMutex       sync.RWMutex
	registerAPIServiceListerArgsForCall []FakeAPIRegistrationV1ListerRegisterAPIServiceListerArgs
	invocations                         map[string][][]interface{}
	callOrder                           []string
	invocationsMutex                    sync.RWMutex
}

// FakeAPIRegistrationV1ListerRegisterAPIServiceListerArgs holds the arguments of one call to RegisterAPIServiceLister.
type FakeAPIRegistrationV1ListerRegisterAPIServiceListerArgs struct {
	Arg1 v1.APIServiceLister
}

func (fake *FakeAPIRegistrationV1Lister) APIServiceLister() v1.APIServiceLister {
	fake.aPIServiceListerMutex.Lock()
	ret, specificReturn := fake.aPIServiceListerReturnsOnCall[len(fake.aPIServiceListerArgsForCall)]
	fake.aPIServiceListerArgsForCall = append(fake.aPIServiceListerArgsForCall, struct{}{})
	stub := fake.APIServiceListerStub
	fakeReturns := fake.aPIServiceListerReturns
	fake.recordInvocation("APIServiceLister", []interface{}{})
	fake.aPIServiceListerMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAPIRegistrationV1Lister) APIServiceListerCallCount() int {
	fake.aPIServiceListerMutex.RLock()
	defer fake.aPIServiceListerMutex.RUnlock()
	return len(fake.aPIServiceListerArgsForCall)
}

func (fake *FakeAPIRegistrationV1Lister) APIServiceListerCalls(stub func() v1.APIServiceLister) {
	fake.aPIServiceListerMutex.Lock()
	defer fake.aPIServiceListerMutex.Unlock()
	fake.APIServiceListerStub = stub
}

func (fake *FakeAPIRegistrationV1Lister) APIServiceListerReturns(result1 v1.APIServiceLister) {
	fake.aPIServiceListerMutex.Lock()
	defer fake.aPIServiceListerMutex.Unlock()
	fake.APIServiceListerStub = nil
	fake.aPIServiceListerReturns = struct {
		result1 v1.APIServiceLister
	}{result1}
}

func (fake *FakeAPIRegistrationV1Lister) APIServiceListerReturnsOnCall(i int, result1 v1.APIServiceLister) {
	fake.aPIServiceListerMutex.Lock()
	defer fake.aPIServiceListerMutex.Unlock()
	fake.APIServiceListerStub = nil
	if fake.aPIServiceListerReturnsOnCall == nil {
		fake.aPIServiceListerReturnsOnCall = make(map[int]struct {
			result1 v1.APIServiceLister
		})
	}
	fake.aPIServiceListerReturnsOnCall[i] = struct {
		result1 v1.APIServiceLister
	}{result1}
}

func (fake *FakeAPIRegistrationV1Lister) RegisterAPIServiceLister(arg1 v1.APIServiceLister) {
	fake.registerAPIServiceListerMutex.Lock()
	fake.registerAPIServiceListerArgsForCall = append(fake.registerAPIServiceListerArgsForCall, FakeAPIRegistrationV1ListerRegisterAPIServiceListerArgs{arg1})
	stub := fake.RegisterAPIServiceListerStub
	fake.recordInvocation("RegisterAPIServiceLister", []interface{}{arg1})
	fake.registerAPIServiceListerMutex.Unlock()
	if stub != nil {
		stub(arg1)
	}
}

func (fake *FakeAPIRegistrationV1Lister) RegisterAPIServiceListerCallCount() int {
	fake.registerAPIServiceListerMutex.RLock()
	defer fake.registerAPIServiceListerMutex.RUnlock()
	return len(fake.registerAPIServiceListerArgsForCall)
}

func (fake *FakeAPIRegistrationV1Lister) RegisterAPIServiceListerCalls(stub func(v1.APIServiceLister)) {
	fake.registerAPIServiceListerMutex.Lock()
	defer fake.registerAPIServiceListerMutex.Unlock()
	fake.RegisterAPIServiceListerStub = stub
}

func (fake *FakeAPIRegistrationV1Lister) RegisterAPIServiceListerArgsForCall(i int) v1.APIServiceLister {
	fake.registerAPIServiceListerMutex.RLock()
	defer fake.registerAPIServiceListerMutex.RUnlock()
	argsForCall := fake.registerAPIServiceListerArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeAPIRegistrationV1Lister) RegisterAPIServiceListerArgs() []FakeAPIRegistrationV1ListerRegisterAPIServiceListerArgs {
	fake.registerAPIServiceListerMutex.RLock()
	defer fake.registerAPIServiceListerMutex.RUnlock()
	args := make([]FakeAPIRegistrationV1ListerRegisterAPIServiceListerArgs, len(fake.registerAPIServiceListerArgsForCall))
	copy(args, fake.registerAPIServiceListerArgsForCall)
	return args
}

func (fake *FakeAPIRegistrationV1Lister) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAPIRegistrationV1Lister) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeAPIRegistrationV1Lister) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ operatorlister.APIRegistrationV1Lister = new(FakeAPIRegistrationV1Lister)
