apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-operator
  namespace: {{ .Values.namespace }}
  labels:
    app: catalog-operator
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.catalog.replicaCount }}
  selector:
    matchLabels:
      app: catalog-operator
  template:
    metadata:
      labels:
        app: catalog-operator
    spec:
      serviceAccountName: alm-operator-serviceaccount
      containers:
        - name: catalog-operator
          command:
          - /bin/catalog
          {{- if .Values.watchedNamespaces }}
          - -watchedNamespaces
          - {{ .Values.watchedNamespaces }}
          {{- end }}
          - '-namespace'
          - {{ .Values.catalog_namespace }}
          - '-debug'
          image: {{ .Values.catalog.image.ref }}
          imagePullPolicy: {{ .Values.catalog.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.catalog.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.catalog.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.catalog.service.internalPort }}
          {{- if .Values.catalog.resources }}
          resources:
{{ toYaml .Values.catalog.resources | indent 12 }}
          {{- end}}
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      imagePullSecrets:
        - name: coreos-pull-secret
