// +build !ignore_autogenerated

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1alpha1

import (
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	reflect "reflect"
)

// GetGeneratedDeepCopyFuncs returns the generated funcs, since we aren't registering them.
//
// Deprecated: deepcopy registration will go away when static deepcopy is fully implemented.
func GetGeneratedDeepCopyFuncs() []conversion.GeneratedDeepCopyFunc {
	return []conversion.GeneratedDeepCopyFunc{
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*AlphaCatalogEntry).DeepCopyInto(out.(*AlphaCatalogEntry))
			return nil
		}, InType: reflect.TypeOf(&AlphaCatalogEntry{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*AlphaCatalogEntryList).DeepCopyInto(out.(*AlphaCatalogEntryList))
			return nil
		}, InType: reflect.TypeOf(&AlphaCatalogEntryList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*AlphaCatalogEntrySpec).DeepCopyInto(out.(*AlphaCatalogEntrySpec))
			return nil
		}, InType: reflect.TypeOf(&AlphaCatalogEntrySpec{})},
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlphaCatalogEntry) DeepCopyInto(out *AlphaCatalogEntry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		if *in == nil {
			*out = nil
		} else {
			*out = new(AlphaCatalogEntrySpec)
			(*in).DeepCopyInto(*out)
		}
	}
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlphaCatalogEntry.
func (in *AlphaCatalogEntry) DeepCopy() *AlphaCatalogEntry {
	if in == nil {
		return nil
	}
	out := new(AlphaCatalogEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlphaCatalogEntry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlphaCatalogEntryList) DeepCopyInto(out *AlphaCatalogEntryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]*AlphaCatalogEntrySpec, len(*in))
		for i := range *in {
			if (*in)[i] == nil {
				(*out)[i] = nil
			} else {
				(*out)[i] = new(AlphaCatalogEntrySpec)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlphaCatalogEntryList.
func (in *AlphaCatalogEntryList) DeepCopy() *AlphaCatalogEntryList {
	if in == nil {
		return nil
	}
	out := new(AlphaCatalogEntryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlphaCatalogEntryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlphaCatalogEntrySpec) DeepCopyInto(out *AlphaCatalogEntrySpec) {
	*out = *in
	in.ClusterServiceVersionSpec.DeepCopyInto(&out.ClusterServiceVersionSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlphaCatalogEntrySpec.
func (in *AlphaCatalogEntrySpec) DeepCopy() *AlphaCatalogEntrySpec {
	if in == nil {
		return nil
	}
	out := new(AlphaCatalogEntrySpec)
	in.DeepCopyInto(out)
	return out
}
