// +build !ignore_autogenerated

/*
Copyright Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package available

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailableClusterServiceVersion) DeepCopyInto(out *AvailableClusterServiceVersion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailableClusterServiceVersion.
func (in *AvailableClusterServiceVersion) DeepCopy() *AvailableClusterServiceVersion {
	if in == nil {
		return nil
	}
	out := new(AvailableClusterServiceVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AvailableClusterServiceVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailableClusterServiceVersionList) DeepCopyInto(out *AvailableClusterServiceVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AvailableClusterServiceVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailableClusterServiceVersionList.
func (in *AvailableClusterServiceVersionList) DeepCopy() *AvailableClusterServiceVersionList {
	if in == nil {
		return nil
	}
	out := new(AvailableClusterServiceVersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AvailableClusterServiceVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailableClusterServiceVersionSpec) DeepCopyInto(out *AvailableClusterServiceVersionSpec) {
	*out = *in
	in.ClusterServiceVersionSpec.DeepCopyInto(&out.ClusterServiceVersionSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailableClusterServiceVersionSpec.
func (in *AvailableClusterServiceVersionSpec) DeepCopy() *AvailableClusterServiceVersionSpec {
	if in == nil {
		return nil
	}
	out := new(AvailableClusterServiceVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailableClusterServiceVersionStatus) DeepCopyInto(out *AvailableClusterServiceVersionStatus) {
	*out = *in
	in.ClusterServiceVersionStatus.DeepCopyInto(&out.ClusterServiceVersionStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailableClusterServiceVersionStatus.
func (in *AvailableClusterServiceVersionStatus) DeepCopy() *AvailableClusterServiceVersionStatus {
	if in == nil {
		return nil
	}
	out := new(AvailableClusterServiceVersionStatus)
	in.DeepCopyInto(out)
	return out
}
