apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reportgenerationqueries.metering.openshift.io
  annotations:
    catalog.app.coreos.com/displayName: "Metering generation query"
    catalog.app.coreos.com/description: "A SQL query used by Metering to generate reports"
spec:
  group: metering.openshift.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: reportgenerationqueries
    singular: reportgenerationquery
    kind: ReportGenerationQuery
    shortNames:
    - rgq
  additionalPrinterColumns:
  - name: View Disabled
    type: string
    JSONPath: .spec.view.disabled
  - name: View Name
    type: string
    JSONPath: .status.viewName
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
