apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata: 
  name: etcdcluster-v1s.etcd.database.coreos.com
  labels:
    alm-status-descriptors: etcdoperator.v0.5.1
    alm-owner-etcd: etcd.clusterserviceversionv1s.app.coreos.com.v1alpha1
    operated-by: etcdoperator.v0.5.1
spec:
  group: etcd.database.coreos.com
  version: v1beta2
  scope: Namespaced
  validation:
    openAPIv3:
      type: object
      description: Represents a single instance of etcd
      additionalProperties: false
      required:
      - version
      properties:
        version:
          type: string
          description: Version string
          pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
          x-descriptors:
          - urn:alm:descriptor:versioning:semver
        size:
          type: number
          description: The size of the etcd cluster
          min: 1
          max: 9
          x-descriptors:
          - urn:alm:descriptor:pod:count
          - urn:alm:descriptor:number:integer
        template:
          type: object
          description: Template for fields of subresources
          labels:
            type: object
            description: Labels to apply to associated resources
  names:
    plural: etcdcluster-v1s
    singular: etcdcluster-v1
    kind: EtcdCluster-v1
    listKind: EtcdClusterList-v1
