apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata: 
  name: apptypes.app.coreos.com
spec: 
  group: app.coreos.com
  version: v1
  scope: Namespaced
  names: 
    plural: apptypes
    singular: apptype
    kind: AppType
    shortNames: 
    - at
 
