name: rebase pull request
on:
  push:
    branches:
    - master
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/rebase@v1
        with:
          base: master
      - name: Send failure message
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ failure() }}
        with:
          issue-number: ${{ github.event.issue.number || github.event.number }}
          body: |
            Automatic rebasing for this PR has failed. You'll need to manually
            rebase against the default branch.
