apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alertmanagers.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  version: v1
  scope: Namespaced
  names:
    plural: alertmanagers
    singular: alertmanager
    kind: Alertmanager
    listKind: AlertmanagerList
    shortNames:
      - alertman
      - alrtman
